name: ron4ff
description: A Free Fire UID lookup app.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure this matches your Flutter SDK version requirement, >=3.0.0 is common

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # For making API calls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
